import { Head, Link, usePage } from '@inertiajs/react';
import { Pencil, Plus, Shield, Trash } from 'lucide-react';
import Heading from '@/components/heading';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import { create, destroy, edit, index } from '@/routes/roles';
import type { BreadcrumbItem } from '@/types';
import type { RoleRow } from '@/types/permissions';

type RolesIndexProps = {
    roles: RoleRow[];
};

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Roles',
        href: index(),
    },
];

export default function RolesIndex({ roles }: RolesIndexProps) {
    const { auth } = usePage().props;

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Roles" />
            <div className="flex h-full flex-1 flex-col gap-4 p-4">
                <div className="flex items-start justify-between gap-4">
                    <Heading
                        title="Roles"
                        description="Create roles from the permissions generated by application policies."
                    />
                    {auth.can.roles.create && (
                        <Button asChild>
                            <Link href={create()}>
                                <Plus className="h-4 w-4" />
                                New role
                            </Link>
                        </Button>
                    )}
                </div>
                <Card>
                    <CardContent className="p-0">
                        <div className="overflow-x-auto">
                            <table className="w-full text-sm">
                                <thead>
                                    <tr className="border-b text-left text-muted-foreground">
                                        <th className="px-6 py-3 font-medium">Name</th>
                                        <th className="px-6 py-3 font-medium">Permissions</th>
                                        <th className="flex justify-end px-6 py-3 font-medium">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {roles.length === 0 ? (
                                        <tr>
                                            <td
                                                colSpan={3}
                                                className="px-6 py-8 text-center text-muted-foreground"
                                            >
                                                No roles found.
                                            </td>
                                        </tr>
                                    ) : (
                                        roles.map((role) => (
                                            <tr key={role.id} className="border-b last:border-0">
                                                <td className="px-6 py-3 font-medium">
                                                    <div className="flex items-center gap-2">
                                                        <Shield className="h-4 w-4 text-muted-foreground" />
                                                        {role.name}
                                                    </div>
                                                </td>
                                                <td className="px-6 py-3">
                                                    <div className="flex flex-wrap gap-1">
                                                        {role.permissions.length === 0 ? (
                                                            <span className="text-muted-foreground">
                                                                No permissions
                                                            </span>
                                                        ) : (
                                                            role.permissions.map((permission) => (
                                                                <Badge key={permission} variant="secondary">
                                                                    {permission}
                                                                </Badge>
                                                            ))
                                                        )}
                                                    </div>
                                                </td>
                                                <td className="flex justify-end gap-2 px-6 py-3">
                                                    {auth.can.roles.update && (
                                                        <Button asChild variant="outline" size="sm">
                                                            <Link href={edit(role.id)}>
                                                                <Pencil className="mr-2 h-4 w-4" />
                                                                Edit
                                                            </Link>
                                                        </Button>
                                                    )}
                                                    {auth.can.roles.delete && !role.is_protected && (
                                                        <Button asChild variant="outline" size="sm">
                                                            <Link
                                                                href={destroy(role.id)}
                                                                as="button"
                                                                method="delete"
                                                            >
                                                                <Trash className="mr-2 h-4 w-4" />
                                                                Delete
                                                            </Link>
                                                        </Button>
                                                    )}
                                                </td>
                                            </tr>
                                        ))
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
